version: '3.0'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana/

volumes:
  prometheus: {}
  grafana: {}
